"""Request/response DTOs for the WebApp API, grouped by feature.

Re-exports everything so callers can do `from app.models.webapp import X`
instead of reaching into the individual feature modules.
"""

from app.models.webapp.auth import (
    LogoutRequest,
    PhoneLoginStartRequest,
    PhoneLoginVerifyRequest,
    WebAccountChangePasswordRequest,
    WebAccountChangePasswordResponse,
    WebAccountCreateRequest,
    WebAccountCreateResponse,
    WebAppChangeResponse,
    WebAppInfoResponse,
    WebAppLoginRequest,
    WebRegistrationModeRequest,
    WebRegistrationModeResponse,
)
from app.models.webapp.balance import (
    BalanceDepositCryptoRequest,
    BalanceDepositCryptoResponse,
    BalanceDepositManualReceiptResponse,
    BalanceDepositManualRequest,
    BalanceDepositManualResponse,
    BalanceMethodsRequest,
    BalanceMethodsResponse,
)
from app.models.webapp.buy import (
    WebAppBuyConfirmRequest,
    WebAppBuyConfirmResponse,
    WebAppBuyOptionsRequest,
    WebAppBuyOptionsResponse,
    WebAppBuyPanelItem,
    WebAppBuyPlanItem,
    WebAppBuyPlansRequest,
    WebAppBuyPlansResponse,
    WebAppBuyPreviewRequest,
    WebAppBuyPreviewResponse,
    WebAppBuyUsernameRequest,
    WebAppBuyUsernameResponse,
)
from app.models.webapp.common import (
    DiscountInfo,
    ServiceButtons,
    ServiceStatus,
    TransactionStats,
    TransactionStatsSummary,
    UserProfile,
    WebAppAuthRequest,
    WebAppUserData,
)
from app.models.webapp.renew import (
    RenewPlanItem,
    WebAppRenewConfirmRequest,
    WebAppRenewConfirmResponse,
    WebAppRenewOptionsRequest,
    WebAppRenewOptionsResponse,
)
from app.models.webapp.services import (
    PanelGroupItem,
    WebAppChangeLinkRequest,
    WebAppChangeSubscriptionRequest,
    WebAppClientItem,
    WebAppClientsRequest,
    WebAppClientsResponse,
    WebAppConfigLinkItem,
    WebAppConfigLinksRequest,
    WebAppConfigLinksResponse,
    WebAppServiceDetailRequest,
    WebAppServiceDetailResponse,
    WebAppServicesRequest,
    WebAppServicesResponse,
)
from app.models.webapp.transactions import (
    WebAppTransactionItem,
    WebAppTransactionsRequest,
    WebAppTransactionsResponse,
)
from app.models.webapp.usage_chart import (
    WebAppUsageChartDayItem,
    WebAppUsageChartNodeItem,
    WebAppUsageChartRequest,
    WebAppUsageChartResponse,
    WebAppUsageChartSeriesItem,
)

__all__ = [
    "BalanceDepositCryptoRequest",
    "BalanceDepositCryptoResponse",
    "BalanceDepositManualReceiptResponse",
    "BalanceDepositManualRequest",
    "BalanceDepositManualResponse",
    "BalanceMethodsRequest",
    "BalanceMethodsResponse",
    "DiscountInfo",
    "LogoutRequest",
    "PanelGroupItem",
    "PhoneLoginStartRequest",
    "PhoneLoginVerifyRequest",
    "RenewPlanItem",
    "ServiceButtons",
    "ServiceStatus",
    "TransactionStats",
    "TransactionStatsSummary",
    "UserProfile",
    "WebAccountChangePasswordRequest",
    "WebAccountChangePasswordResponse",
    "WebAccountCreateRequest",
    "WebAccountCreateResponse",
    "WebAppAuthRequest",
    "WebAppBuyConfirmRequest",
    "WebAppBuyConfirmResponse",
    "WebAppBuyOptionsRequest",
    "WebAppBuyOptionsResponse",
    "WebAppBuyPanelItem",
    "WebAppBuyPlanItem",
    "WebAppBuyPlansRequest",
    "WebAppBuyPlansResponse",
    "WebAppBuyPreviewRequest",
    "WebAppBuyPreviewResponse",
    "WebAppBuyUsernameRequest",
    "WebAppBuyUsernameResponse",
    "WebAppChangeLinkRequest",
    "WebAppChangeResponse",
    "WebAppChangeSubscriptionRequest",
    "WebAppClientItem",
    "WebAppClientsRequest",
    "WebAppClientsResponse",
    "WebAppConfigLinkItem",
    "WebAppConfigLinksRequest",
    "WebAppConfigLinksResponse",
    "WebAppInfoResponse",
    "WebAppLoginRequest",
    "WebAppRenewConfirmRequest",
    "WebAppRenewConfirmResponse",
    "WebAppRenewOptionsRequest",
    "WebAppRenewOptionsResponse",
    "WebAppServiceDetailRequest",
    "WebAppServiceDetailResponse",
    "WebAppServicesRequest",
    "WebAppServicesResponse",
    "WebAppTransactionItem",
    "WebAppTransactionsRequest",
    "WebAppTransactionsResponse",
    "WebAppUsageChartDayItem",
    "WebAppUsageChartNodeItem",
    "WebAppUsageChartRequest",
    "WebAppUsageChartResponse",
    "WebAppUsageChartSeriesItem",
    "WebAppUserData",
    "WebRegistrationModeRequest",
    "WebRegistrationModeResponse",
]
