"""add percentage referral reward

Revision ID: a7d4c2e9f1b3
Revises: f3b8a1d6c2e4
Create Date: 2026-10-09 18:04:37.215094

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7d4c2e9f1b3'
down_revision: str | None = 'f3b8a1d6c2e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_settings', sa.Column('referral_reward_mode', sa.String(length=10), server_default='fixed', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_reward_percent', sa.Integer(), server_default='10', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_reward_max', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_bonus_mode', sa.String(length=10), server_default='fixed', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_bonus_percent', sa.Integer(), server_default='5', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_bonus_max', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('referral_rewards', sa.Column('base_amount', sa.BigInteger(), nullable=True))
    op.add_column('referral_rewards', sa.Column('reward_percent', sa.Integer(), nullable=True))
    op.add_column('referral_rewards', sa.Column('bonus_percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_rewards', 'bonus_percent')
    op.drop_column('referral_rewards', 'reward_percent')
    op.drop_column('referral_rewards', 'base_amount')
    op.drop_column('referral_settings', 'referral_bonus_max')
    op.drop_column('referral_settings', 'referral_bonus_percent')
    op.drop_column('referral_settings', 'referral_bonus_mode')
    op.drop_column('referral_settings', 'referral_reward_max')
    op.drop_column('referral_settings', 'referral_reward_percent')
    op.drop_column('referral_settings', 'referral_reward_mode')
    # ### end Alembic commands ###
