"""add referral payouts

Revision ID: c5e8b1f4a2d6
Revises: a7d4c2e9f1b3
Create Date: 2026-10-09 21:12:53.608417

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5e8b1f4a2d6'
down_revision: str | None = 'a7d4c2e9f1b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('card_holder', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refpayouts_user', 'referral_payouts', ['user_id'], unique=False)
    op.create_index('ix_refpayouts_status', 'referral_payouts', ['status'], unique=False)
    op.add_column('referral_rewards', sa.Column('payout_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_refrewards_payout', 'referral_rewards', ['payout_id'], unique=False)
    op.add_column('referral_settings', sa.Column('referral_reward_destination', sa.String(length=10), server_default='wallet', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_withdraw_enabled', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_withdraw_min', sa.BigInteger(), server_default='50000', nullable=False))
    op.add_column('referral_settings', sa.Column('referral_transfer_enabled', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_settings', 'referral_transfer_enabled')
    op.drop_column('referral_settings', 'referral_withdraw_min')
    op.drop_column('referral_settings', 'referral_withdraw_enabled')
    op.drop_column('referral_settings', 'referral_reward_destination')
    op.drop_index('ix_refrewards_payout', table_name='referral_rewards')
    op.drop_column('referral_rewards', 'payout_id')
    op.drop_index('ix_refpayouts_status', table_name='referral_payouts')
    op.drop_index('ix_refpayouts_user', table_name='referral_payouts')
    op.drop_table('referral_payouts')
    # ### end Alembic commands ###
